### ISSUE TITLE
Adapters for data that comes back from API queries

### ISSUE THREAD

**Issue by CindySchalit** [escape-hatch/escapehatch#37]
Much of the data that is being returned from the API queries needs to be cleaned up before it reaches the front end.

For an example of such adapter, see lines 18 through 29 in server/api/search/index.js

**Comment by glebec** [comment]
As an example, you might have:

* `githubAPI.js` – a module whose sole purpose is to make HTTP requests to the API and give promises for results, with little to no processing. Some "fair game" processing might include converting date numbers to Date objects, and HTML-encoded strings to regular strings.
* `githubAdapter.js` – a module which serves as an intermediary between the API module and bits of the app interested in GitHub results. Can do more aggressive transformations, e.g. only plucking the `data.items` array and dropping everything else, renaming or adding keys (e.g. `vendor: 'GitHub'`), and other normalizations. I think you may have a module like this already.
* routers and other modules will probably use `githubAdapter.js`, not other the lower-level `githubAPI.js`.
