### ISSUE TITLE
Improve gitignore

### ISSUE THREAD

**Issue by glebec** [escape-hatch/escapehatch#4]
There are files often created and accidentally added to a repo, including but not limited to:

* log files (e.g. npm error log)
* DS_Store files (OS X folder metadata)
* IDE files (e.g. VSC settings)

Suggest making your `gitignore` more robust, for example using [this one](https://github.com/FullstackAcademy/1704-FSA-RM-Library/blob/master/.gitignore) as a template.

**Comment by aperez25** [comment]
Updated, thanks Gabe for the template!
