### ISSUE TITLE
Design - Login Page

### ISSUE THREAD

**Issue by jenktam** [escape-hatch/escapehatch#69]

**Comment by aperez25** [comment]
@jenktam don't know if you're working on this over break, but I'm getting 'logged in' automatically even though google login isn't working. When I hit backspace on the callback url error page, the site is using a dummy account, 'alice@alice.com', to log me in, not sure why.

**Comment by jenktam** [comment]
Hi @aperez25. I tried to replicate the issue and could not see the same issue on my end. Let's talk about it in more detail today.
